spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19770507
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
env: dev2000
